"""Initial migration

Revision ID: 47883de1bc46
Revises: 
Create Date: 2024-05-04 16:42:44.213896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47883de1bc46'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('alias', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request_class_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=False),
    sa.Column('request_class_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['request_class_id'], ['request_classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activation_question', sa.String(length=100), nullable=False),
    sa.Column('request_class_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['request_class_id'], ['request_classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenario_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ordi', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=100), nullable=False),
    sa.Column('possible_answers', sa.String(length=500), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scenario_steps')
    op.drop_table('scenarios')
    op.drop_table('request_class_links')
    op.drop_table('request_classes')
    # ### end Alembic commands ###
